import { supabase } from "@/api/supabaseClient";

function formatDateDMY(isoStr) {
  if (!isoStr) return "";
  const part = String(isoStr).substring(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(part)) return isoStr;
  const [yyyy, mm, dd] = part.split("-");
  return `${dd}/${mm}/${yyyy}`;
}

function addDaysDMY(isoDateStr, days) {
  const part = String(isoDateStr || "").substring(0, 10);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(part)) return "";
  const [y, m, d] = part.split("-").map(Number);
  const dt = new Date(y, m - 1, d + days);
  return `${String(dt.getDate()).padStart(2, "0")}/${String(dt.getMonth() + 1).padStart(2, "0")}/${dt.getFullYear()}`;
}

function buildCookDateMap(jobs) {
  const map = {};
  for (const j of (jobs || [])) {
    const k = (j.menu_item_code || "").toLowerCase().trim();
    if (!map[k] || j.cook_date > map[k]) map[k] = j.cook_date;
  }
  return map;
}

async function buildLpJobMap() {
  // Query both sources in parallel; meal_count_jobs overrides predictions when populated
  const [jobsRes, predRes] = await Promise.all([
    supabase
      .from("meal_count_jobs")
      .select("menu_item_code, lp_item_id")
      .not("lp_item_id", "is", null),
    supabase
      .from("imported_meal_predictions")
      .select("menu_item_code, lp_item_id")
      .not("lp_item_id", "is", null),
  ]);
  const map = {};
  for (const row of (predRes.data || [])) {
    if (row.menu_item_code && row.lp_item_id)
      map[row.menu_item_code.toLowerCase().trim()] = row.lp_item_id;
  }
  for (const row of (jobsRes.data || [])) {
    if (row.menu_item_code && row.lp_item_id)
      map[row.menu_item_code.toLowerCase().trim()] = row.lp_item_id;
  }
  return map;
}

function buildAsnRows(pallets, lpJobMap, cookDateMap) {
  return pallets.flatMap((pallet) => {
    const items = pallet.items || [];
    if (!items.length) return [];
    const item = items[0];
    const code = (item.menu_item_code || "").toLowerCase().trim();
    const cookDate = (pallet.cook_dates || [])[0] || cookDateMap[code] || "";
    const sku = lpJobMap[code] || item.menu_item_code || "";
    const prodIso = (pallet.created_date || "").substring(0, 10);
    const totalQty = items.reduce((s, i) => s + (i.quantity || 0), 0);
    return [
      {
        CONTRACT: "F063",
        SUPPLIER: "F063",
        SKU: sku,
        "QTY (UNITS)": totalQty,
        DELIVERYDATE: formatDateDMY(cookDate),
        REFERENCE: "FriveASN",
        PalletIdentifier: pallet.pallet_id,
        Expirydate: prodIso ? addDaysDMY(prodIso, 7) : "",
        BatchId: "",
        ProductionDate: formatDateDMY(prodIso),
      },
    ];
  });
}

function rowsToCsv(rows) {
  if (!rows.length) return "";
  const headers = Object.keys(rows[0]);
  return [
    headers.join(","),
    ...rows.map((r) => headers.map((h) => `"${r[h] ?? ""}"`).join(",")),
  ].join("\n");
}

export async function sendAsnEmail({ trailer, pallets, jobs = [], recipients }) {
  if (!recipients || !recipients.length) return 0;

  const [lpJobMap, cookDateMap] = await Promise.all([
    buildLpJobMap(),
    Promise.resolve(buildCookDateMap(jobs)),
  ]);

  const rows = buildAsnRows(pallets, lpJobMap, cookDateMap);
  if (!rows.length) return 0;

  const csv = rowsToCsv(rows);

  const firstPallet = pallets[0];
  const cookDate =
    (firstPallet?.cook_dates || [])[0] ||
    cookDateMap[((firstPallet?.items || [])[0]?.menu_item_code || "").toLowerCase().trim()] ||
    trailer.closed_at?.substring(0, 10) ||
    "unknown";

  const trailerId = (trailer.trailer_id_label || trailer.id || "").replace(/\s+/g, "_");
  const filename = `ASN_${trailerId}_${cookDate}.csv`;
  const subject = `ASN Report — ${trailer.trailer_id_label || trailerId} — ${cookDate}`;

  const base64Csv = btoa(unescape(encodeURIComponent(csv)));

  const apiKey = import.meta.env.VITE_RESEND_API_KEY;
  if (!apiKey) throw new Error("VITE_RESEND_API_KEY is not configured");

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      from: "Frive Outbound <onboarding@resend.dev>",
      to: recipients.map((r) => r.email),
      subject,
      text: `ASN Report for trailer ${trailer.trailer_id_label || trailerId}.\n\nPlease find the attached CSV file.\n\nGenerated by Frive Meal Assembly.`,
      attachments: [{ filename, content: base64Csv }],
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.message || `Resend API error: ${res.status}`);
  }

  return recipients.length;
}
